# Generated by Django 5.2.1 on 2025-05-19 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renipress', models.CharField(default='5196', max_length=10, unique=True)),
                ('nombre', models.CharField(default='Hospital Regional Docente de Trujillo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('responsable_pdd', 'Responsable PDD'), ('encargado_pdd', 'Encargado PDD'), ('digitador', 'Digitador'), ('auditor', 'Auditor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FUA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('renipress', models.CharField(default='5196', max_length=10)),
                ('lote', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=8)),
                ('tipo_fua', models.CharField(choices=[('observado', 'Observado'), ('extemporaneo', 'Extemporáneo')], max_length=20)),
                ('tipo_auditoria', models.CharField(choices=[('reconsideracion', 'Reconsideración'), ('pcpp', 'PCPP'), ('fissal', 'FISSAL')], max_length=20)),
                ('estado', models.CharField(choices=[('observado', 'Observado'), ('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('cod_prestacion', models.CharField(max_length=20)),
                ('nombre_prestacion', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fijo', models.CharField(default='180', max_length=10)),
                ('cod_afiliacion', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=8)),
                ('historia_clinica', models.CharField(max_length=20)),
                ('fua', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asegurado', to='sigesor.fua')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prestacion', models.CharField(max_length=20)),
                ('nombre_prestacion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('fua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='sigesor.fua')),
            ],
        ),
    ]
